### ISSUE TITLE
Use map id (not name) when exporting

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1289]
```
Caused by: com.querydsl.core.NonUniqueResultException: Only one result is allowed for fetchOne calls
at com.querydsl.core.support.FetchableQueryBase.uniqueResult(FetchableQueryBase.java:64) ~[querydsl-core-4.2.1.jar:?]
at com.querydsl.sql.ProjectableSQLQuery.fetchOne(ProjectableSQLQuery.java:401) ~[querydsl-sql-4.2.1.jar:?]
at hoot.services.utils.DbUtils.getMapIdByName(DbUtils.java:162) ~[classes/:?]

```

Seems like having private data now allows duplicate names to be saved, which should be find, except the service calls need to reference maps by their id only.

**Comment by brianhatchl** [comment]
Not doing Hoot 1.0 maintenance any longer
