### ISSUE TITLE
investigate maxlistenersexceededWarning

### ISSUE THREAD

**Issue by bobi7** [ngageoint/hootenanny-ui#1504]
```
events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 render-dataset-table listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (http://localhost:8080/iD.min.js:139054:15)
    at Events.addListener (http://localhost:8080/iD.min.js:139070:10)
    at LayerAdd.listen (http://localhost:8080/iD.min.js:15114:21)
    at LayerAdd.render (http://localhost:8080/iD.min.js:14929:14)
    at EnterNode.<anonymous> (http://localhost:8080/iD.min.js:15861:36)
    at Selection.select (http://localhost:8080/iD.min.js:108142:50)
    at Sidebar.createForms (http://localhost:8080/iD.min.js:15859:14)
    at Sidebar.reset (http://localhost:8080/iD.min.js:15952:14)
    at Sidebar.layerRemoved (http://localhost:8080/iD.min.js:15916:18)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/iD.min.js:16171:37)
```

I did a conflate, remove from map, add to map a couple times and it shows up eventually

**Comment by brianhatchl** [comment]
Getting this warning again now that the number is 16.  Find out instead if the listeners are indeed duplicates that can be avoided.
