### ISSUE TITLE
UI failure on CentOS7x

### ISSUE THREAD

**Issue by sputnam** [ngageoint/hootenanny-ui#943]
The following error seems to consistently happen when tests are run on CentOS7x.
```
Unable to find css "text" with text "BrazilFilterCucumber" (Capybara::ElementNotFound)
./features/step_definitions/custom_steps.rb:219:in `/^I click the "([^"]*)" Dataset$/'
./features/support/hooks.rb:43:in `block in <top (required)>'
features/hgis_workflow.feature:19:in `When I click the "BrazilFilterCucumber" Dataset'
```

**Comment by sputnam** [comment]
![screenshot_2017-11-10-18-40-57 803](https://user-images.githubusercontent.com/4978479/32680018-fc687cee-c625-11e7-9f97-6c5c5d0edb70.png)

**Comment by rmrice** [comment]
Those alerts are probably blocking the driver from accessing elements under it (aka `BrazilFilterCucumber`).

**Comment by brianhatchl** [comment]
Should be a stack trace in tomcat log.  Or you could run through this manually and `more details` to get stderr.
